[#10742] [Spark connector] Handle extra backtick in tokenRangeToCqlQuery for Spark 3.2
Summary:
The output of Spark 3.2.0 Plan contains backticks:
```
 - Cassandra Filters: [[`phone->'key'->1->'m'->2->>'b'` = ?, 400]]
```
When the query is passed to CQL, CQL complains:
```
java.io.IOException: Exception during preparation of SELECT "id", "address", phone->'key'->1->'m'->2->'b' FROM test.person WHERE token("id") < ? AND `phone->'key'->1->'m'->2->>'b'` = ?   ALLOW FILTERING: Invalid CQL Statement
SELECT "id", "address", phone->'key'->1->'m'->2->'b' FROM test.person WHERE token("id") < ? AND `phone->'key'->1->'m'->2->>'b'` = ?   ALLOW FILTERING
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Invalid CQL Statement
SELECT "id", "address", phone->'key'->1->'m'->2->'b' FROM test.person WHERE token("id") < ? AND `phone->'key'->1->'m'->2->>'b'` = ?   ALLOW FILTERING
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 (ql error -12)
    at com.datastax.spark.connector.datasource.ScanHelper$.prepareScanStatement(ScanHelper.scala:152)
    at com.datastax.spark.connector.datasource.ScanHelper$.fetchTokenRange(ScanHelper.scala:74)
    at com.datastax.spark.connector.datasource.CassandraPartitionReaderBase.$anonfun$getIterator$1(CassandraScanPartitionReaderFactory.scala:108)
```
Spark connector needs to handle the backticks by removing them before passing to CQL.

Test Plan: mvn test -Dtest=org.yb.loadtest.TestSpark3Jsonb

Reviewers: nkumar, skumar

Reviewed By: skumar

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D15983