[#8115] Reference the correct BuildSide class in Spark 3.1
Summary:
When running job with Spark 3.1, we would see the following exception due to Spark connector referencing relocated Spark 3.1 class
```
557 [ERROR] testJsonb(org.yb.loadtest.TestSpark3Jsonb)  Time elapsed: 5.827 s  <<< ERROR!
558 java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/joins/package$BuildSide
559         at org.yb.loadtest.TestSpark3Jsonb.testJsonb(TestSpark3Jsonb.java:97)
```
This revision changes reference to BuildSide for Spark 3.1.x release
The following changes from upstream are included:

SPARKC-626 CassandraSparkExtensions crash with Spark 3.1.0
SPARKC-646 adjust direct join strategy to Spark 3.1

Test Plan: Run TestSparkJsonb against Spark 3.1.1 release.

Reviewers: hbhanawat, nkumar, skumar

Reviewed By: skumar

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D11390