[#8610] Spark Connector: Add writer option for quoting jsonb fields as strings
Summary:
This revision adds a WriteConf entry:
```
spark.cassandra.json.quoteValueString
```
Whether the JSONB field values should be quoted as string. Defaulting to false (since this is not space efficient).

The option would allow preserving floating point precision for jsonb fields.
For un-quoted non-numeric values, double quotes are added. Otherwise such value would be rejected by CQL.

Refer to ZD 1029 for background.

Test Plan:
By altering an input value in java/yb-cql-4x/src/test/resources/cdr-call.csv to 100.1, observe the following in test output (note the additional quotes):
```
org.junit.ComparisonFailure: expected:<{"dl":1122,"rsrp":["abc","rsrq":null,"sinr":"100.1"],"ul":72}> but was:<{"dl":1122,"rsrp":[-80,"rsrq":null,"sinr":100],"ul":72}>
    at org.yb.loadtest.TestSpark3Jsonb.testCdr(TestSpark3Jsonb.java:193)
```

Reviewers: hbhanawat, skumar, mihnea

Reviewed By: mihnea

Subscribers: yql

Differential Revision: https://phabricator.dev.yugabyte.com/D11714