[#8849] Spark connector: Return proper value for unspported Filter in FilterOps#columnName
Summary:
Currently when OR expression is used in where clause:
```
            String selectQuery = "Select id,name,address,phone from mycatalog." + tableWithKeysapce
                    + " where id = 2 or id = 3 order by id";
```
we would get the following exception:
```
2021-06-10 16:46:37,742 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.loadtest.TestJsonUpsert", method="testUpsertJsonb"
java.lang.IllegalArgumentException: Don't know how to get column name from the predicate: Or(EqualTo(id,2),EqualTo(id,3))
```
Instead of throwing exception from FilterOps#columnName for unspported Filter, we can return a dummy String which indicates to isJsonObjPredicate() that the Filter is not json predicate.

Test Plan:
Run TestJsonUpsert with the following query:
```
            String selectQuery = "Select id,name,address,phone from mycatalog." + tableWithKeysapce
                    + " where id = 2 or id = 3 order by id";
```
verify, via assertions, that proper rows are returned.

Reviewers: hbhanawat, skumar, mihnea, nkumar

Reviewed By: nkumar

Subscribers: nkumar, yql

Differential Revision: https://phabricator.dev.yugabyte.com/D11884